# Generated by Django 3.2.7 on 2023-04-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('phone_number', models.CharField(max_length=120, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание2')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('hours', models.CharField(blank=True, max_length=200, verbose_name='время')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantsinfos', to='myapp.menucategory')),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='названи еды')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='цена')),
                ('image', models.ImageField(upload_to='MenuItem/', verbose_name='Фото')),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='myapp.menucategory')),
            ],
            options={
                'verbose_name': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('message', models.TextField(verbose_name='обращение для посетителей')),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactinfos', to='myapp.menucategory')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('image', models.ImageField(upload_to='ComingSoon/', verbose_name='Фото')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создание')),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comsoon', to='myapp.menucategory')),
            ],
            options={
                'verbose_name': 'Скоро выйдет',
            },
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('review', models.TextField(blank=True, verbose_name='Отзыв')),
                ('star_nbr', models.IntegerField()),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rewiwes', to='myapp.menucategory')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
