# Generated by Django 3.2.7 on 2023-04-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230427_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantinfo',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О наc'},
        ),
    ]
