# Generated by Django 3.2.7 on 2023-04-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_restaurantinfo_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCategory',
            new_name='Home_restaurant',
        ),
        migrations.AlterModelOptions(
            name='home_restaurant',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.RenameField(
            model_name='clientreview',
            old_name='menu_category',
            new_name='home_restaurant',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='menu_category',
            new_name='home_restaurant',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_category',
            new_name='home_restaurant',
        ),
        migrations.RenameField(
            model_name='restaurantinfo',
            old_name='menu_category',
            new_name='home_restaurant',
        ),
    ]
